### ISSUE TITLE
关于位置编码实现的疑问

### ISSUE THREAD

**Issue by zhijiezhong** [AlvinIsonomia/PADEL#1]
你好，很开心能见到这么好的一个工作。

我对这个位置编码的实现有点疑问，在model.py中的class PositionEncoding(nn.Module)，实现位置编码时为什么dist_matrix初始化的时候维度是([len(self.graph) + 1, len(self.graph) + 1])的，不应该是([len(self.graph), len(self.graph)])吗？尽管好像在最后会删除掉，变成([len(self.graph), len(self.graph)])，我有点不明白为什么不直接初始化成([len(self.graph), len(self.graph)])。

期待您的回复，谢谢！

**Comment by AlvinIsonomia** [comment]
感谢您对我们工作的关注！

在构建子图数据集时，为了方便并行，我们会给对每个子图的进行padding，比如在邻接矩阵加入全0的行和全0的列。len(self.graph+1)是一开始实现的时候想着要给padding的节点留地方……之后发现好像不需要这个操作，但是因为写的时候图方便还是现在的实现。

**Comment by zhijiezhong** [comment]
ok，明白，感谢您的回复
